# Generated by Django 3.0.4 on 2020-03-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200319_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.IntegerField(),
        ),
    ]
